- name: variables
  hosts: localhost
  vars:  #variable declaration
    course: "Ansible"
    Trainer: "Shiva"
    Duration: "120hrs"
  tasks:
  - name: Print information
    vars:  # Task level variable
      course: "DevOps"
    ansible.builtin.debug:
      msg: "Hello i am learning {{course}} from {{Trainer}}, duration is {{Duration}}"