- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: Print information
    ansible.builtin.debug:
      msg: "Hello i am learning {{course}} from {{Trainer}}, duration is {{Duration}}"