- name: data types
  hosts: localhost
  vars:
    course: DevOps with aws  # string
    Tools: #list
    - Linux
    - ansible
    - terraform
    Experience:  #Map or Dictionary
      DevOps: 3 #number
      AWS: 2
      Docker: 1
    RealProject: true #boolean
  tasks:
  - name: Print variables
    ansible.builtin.debug:
      msg: "Cousrse: {{course}},Tools covered {{Tools}}, Experience is  {{Experience}}, is real project {{RealProject}}"

