- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{COURSE | default('AWS')}}"

- name: upper case
  hosts: localhost
  vars:
    greetings: "Hello, good Morning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 3, 4, 4, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"